gammaswap/v1-implementations

.github/workflows/main.yml, .github/workflows/pr.yml, .gitignore, contracts/interfaces/external/cpmm/ICPMM.sol, contracts/strategies/cpmm/base/CPMMBaseStrategy.sol, contracts/test/strategies/cpmm/TestCPMMRepayStrategy.sol, package.json, yarn.lock
-update to v1-core@1.1
-implement syncCFMM function update test contract
-publish packages to github through CI
-update test contracts for removing transfer fees from repay liquidity functions
=> implement syncCFMM function update test contract

contracts/test/strategies/cpmm/TestCPMMLiquidationWithLPStrategy.sol, package.json
-separate cpmm liquidation strategy test into two contracts (one with LP the other with collateral)
=> break up liquidation strategy test int 2 contracts

package.json, yarn.lock
update v1-core to version 1.1.3
=> update v1-core to version 1.1.3

package.json, yarn.lock
-update v1-core version and bump v1-implementations version to 1.1.5
=> update v1-core version  to 1.1.5

contracts/libraries/FullMath.sol, package.json, test/foundry/FullMath.t.sol
-change public to internal and set all view functions as pure in FullMath library
-add natspec and source for functions
-adding safety checks (require statements) to FullMath library
-add more unit tests for FullMath library
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1205929257252386
=> FullMath clean up

contracts/interfaces/external/cpmm/ICPMM.sol, contracts/strategies/cpmm/CPMMShortStrategy.sol, package.json
update _getLatestCFMMReserves to use ERC20 instead of getReserves function
=> use balanceOf for latestCFMMReserves

contracts/libraries/cpmm/CPMMMath.sol, contracts/strategies/cpmm/base/CPMMBaseLongStrategy.sol, contracts/strategies/cpmm/base/CPMMBaseRebalanceStrategy.sol, package.json, test/foundry/CalcDeltasForMaxLP.t.sol, yarn.lock
-update maxLP rebalancing test
-add check for minCollateral when rebalancing to max LP
-add plus 1 to calcPostTradeCollateral function in CPMMMath
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1205984850922686
=> Add safety collateral check to SingleLiquidationStrategy

contracts/interfaces/external/IFeeSource.sol, contracts/strategies/cpmm/base/CPMMBaseLongStrategy.sol, contracts/strategies/cpmm/base/CPMMBaseRebalanceStrategy.sol, contracts/strategies/cpmm/lending/CPMMBorrowStrategy.sol, contracts/strategies/cpmm/lending/CPMMRepayStrategy.sol, contracts/strategies/cpmm/liquidation/CPMMBatchLiquidationStrategy.sol, contracts/strategies/cpmm/liquidation/CPMMExternalLiquidationStrategy.sol, contracts/strategies/cpmm/liquidation/CPMMLiquidationStrategy.sol, contracts/strategies/cpmm/rebalance/CPMMExternalRebalanceStrategy.sol, contracts/test/strategies/cpmm/TestCPMMBatchLiquidationStrategy.sol, contracts/test/strategies/cpmm/TestCPMMBorrowStrategy.sol, contracts/test/strategies/cpmm/TestCPMMExternalRebalanceStrategy.sol, contracts/test/strategies/cpmm/TestCPMMLiquidationStrategy.sol, contracts/test/strategies/cpmm/TestCPMMLiquidationWithLPStrategy.sol, contracts/test/strategies/cpmm/TestCPMMRepayStrategy.sol, package.json, yarn.lock
-external trading fee source for deltaswap
-update unit tests
-round up calcTokensToRepay
-clean up TestCPMMLiquidationStrategy
-update v1-core
=> external trading fee source

contracts/strategies/cpmm/base/CPMMBaseLongStrategy.sol, contracts/strategies/cpmm/base/CPMMBaseRebalanceStrategy.sol, contracts/test/strategies/cpmm/TestCPMMBatchLiquidationStrategy.sol, contracts/test/strategies/cpmm/TestCPMMLiquidationStrategy.sol, contracts/test/strategies/cpmm/TestCPMMRepayStrategy.sol, package.json, yarn.lock
-when feeSource is not set, use hardcoded tradingFee1 in CPMMBaseLongStrategy and CPMMBaseRebalanceStrategy
-implement calcTokensToRepay with maxAmounts
=> Fix fee source bug

contracts/strategies/cpmm/base/CPMMBaseRebalanceStrategy.sol, package.json, test/foundry/CalcDeltasToCloseSetRatio.t.sol
-calcDeltasToCloseSetRatio check ratio before calling math library
-update calcDeltasToCloseSetRatio fuzzing test to check ratio
=> calcDeltasToCloseSetRatio Ratio check

contracts/test/strategies/cpmm/TestCPMMLiquidationStrategy.sol, package.json
-remove borrowLiquidity in TestCPMMLiquidationStrategy.sol
=> Shrink TestCPMMLiquidationStrategy.sol

contracts/test/strategies/cpmm/TestCPMMRepayStrategy.sol, package.json
add lastCFMMTotalSupply to setCFMMReserves in TestCPMMRepayStrategy
=> fix TestCPMMRepayStrategy

contracts/strategies/cpmm/base/CPMMBaseLongStrategy.sol, contracts/test/TestGammaPoolFactory.sol, contracts/test/strategies/cpmm/TestCPMMBaseStrategy.sol, contracts/test/strategies/cpmm/TestCPMMBatchLiquidationStrategy.sol, contracts/test/strategies/cpmm/TestCPMMBorrowStrategy.sol, contracts/test/strategies/cpmm/TestCPMMExternalRebalanceStrategy.sol, contracts/test/strategies/cpmm/TestCPMMLiquidationStrategy.sol, contracts/test/strategies/cpmm/TestCPMMLiquidationWithLPStrategy.sol, contracts/test/strategies/cpmm/TestCPMMRepayStrategy.sol, contracts/test/strategies/cpmm/TestCPMMShortStrategy.sol, package.json, yarn.lock
-update v1-core to version 1.1.14
-change minBorrow() to minPay() in CPMMBaseLongStrategy
=> Upate v1-core version

contracts/test/TestGammaPoolFactory.sol, package.json, yarn.lock
-Update v1core dependency to v1.1.15 version
=> update v1-core 1.1.15

contracts/libraries/FullMath.sol, package.json, yarn.lock
-change view to pure in FullMath library mul512x256()
-update v1-core to 1.1.16 version
=> update v1core to 1.1.16

contracts/test/strategies/cpmm/TestCPMMRepayStrategy.sol, package.json, yarn.lock
-update to 1.1.17
-update test contract TestCPMMRepayStrategy to return tokensHeld too
=> update v1-core version

contracts/test/TestGammaPoolFactory.sol, package.json, yarn.lock
-replace setPoolParams() with execute() in TestGammaPoolFactory
=> update v1-core to version 1.1.22

contracts/pools/CPMMGammaPool.sol, package.json, yarn.lock
-update to v1-core 1.1.21 to lower contract size
-remove tokenCount to lower contract size
=> lower contract size

hardhat.config.ts, package.json, test/foundry/CalcDeltasForMaxLP.t.sol, yarn.lock
-update v1core to version 1.1.22
-add arbsepolia to hardhat config file
=> Upd v1core1.1.22

package.json, yarn.lock
-bump version and update v1-core dependency
=> update v1-core dependency

contracts/test/TestGammaPoolFactory.sol, package.json, yarn.lock
-change removeProtocol to lockProtocol in TestGammaPoolFactory
=> Upd v1core1.1.24

contracts/test/strategies/cpmm/TestCPMMBorrowStrategy.sol, package.json
-pass tradingFee2 in constructor of TestCPMMBorrowStrategy (test contract)
=> Fix: tradingFee2 in TestCPMMBorrowStrategy

contracts/strategies/cpmm/base/CPMMBaseLongStrategy.sol, package.json, yarn.lock
-update v1-core
-check for sufficient rebalancing when repaying liquidity.
=> Feat: token rebalance check

contracts/strategies/cpmm/base/CPMMBaseLongStrategy.sol, contracts/test/strategies/cpmm/TestCPMMBatchLiquidationStrategy.sol, contracts/test/strategies/deltaswap/TestDSV2BatchLiquidationStrategy.sol
-change InsufficientTokeRepayment to  InsufficientTokenRepayment custom error name
=> Fix: Update Custom Error Name

contracts/interfaces/external/deltaswap/IDSPair.sol, contracts/strategies/cpmm/base/CPMMBaseLongStrategy.sol, contracts/strategies/deltaswap/DSV2ShortStrategy.sol, contracts/strategies/deltaswap/lending/DSV2BorrowStrategy.sol, contracts/strategies/deltaswap/lending/DSV2RepayStrategy.sol, contracts/strategies/deltaswap/liquidation/DSV2BatchLiquidationStrategy.sol, contracts/strategies/deltaswap/liquidation/DSV2ExternalLiquidationStrategy.sol, contracts/strategies/deltaswap/liquidation/DSV2LiquidationStrategy.sol, contracts/strategies/deltaswap/rebalance/DSV2ExternalRebalanceStrategy.sol, contracts/test/strategies/cpmm/TestCPMMBatchLiquidationStrategy.sol, contracts/test/strategies/deltaswap/TestDSV2BatchLiquidationStrategy.sol, package.json, yarn.lock
-update deltaswap implementation
=> Feat: updates to deltaswap implementation

contracts/strategies/deltaswap/DSV2ShortStrategy.sol, contracts/strategies/deltaswap/lending/DSV2BorrowStrategy.sol, contracts/strategies/deltaswap/lending/DSV2RepayStrategy.sol, contracts/strategies/deltaswap/liquidation/DSV2BatchLiquidationStrategy.sol, contracts/strategies/deltaswap/liquidation/DSV2ExternalLiquidationStrategy.sol, contracts/strategies/deltaswap/liquidation/DSV2LiquidationStrategy.sol, contracts/strategies/deltaswap/rebalance/DSV2ExternalRebalanceStrategy.sol, package.json
-fix getLPReserves function in deltaswapV2 implementation
=> Fix: getLPReserves in DSV2

contracts/pools/CPMMGammaPoolMain.sol, contracts/strategies/cpmm/base/CPMMBaseLiquidationStrategy.sol, contracts/strategies/cpmm/liquidation/CPMMBatchLiquidationStrategy.sol, contracts/strategies/cpmm/liquidation/CPMMExternalLiquidationStrategy.sol, contracts/strategies/cpmm/liquidation/CPMMLiquidationStrategy.sol, contracts/strategies/deltaswap/liquidation/DSV2BatchLiquidationStrategy.sol, contracts/strategies/deltaswap/liquidation/DSV2ExternalLiquidationStrategy.sol, contracts/strategies/deltaswap/liquidation/DSV2LiquidationStrategy.sol, contracts/test/strategies/cpmm/TestCPMMBatchLiquidationStrategy.sol, contracts/test/strategies/cpmm/TestCPMMLiquidationStrategy.sol, contracts/test/strategies/cpmm/TestCPMMLiquidationWithLPStrategy.sol, contracts/test/strategies/deltaswap/TestDSV2BatchLiquidationStrategy.sol, contracts/test/strategies/deltaswap/TestDSV2LiquidationStrategy.sol, contracts/test/strategies/deltaswap/TestDSV2LiquidationWithLPStrategy.sol, package.json, yarn.lock
-Create CPMMGammaPool version for Mainnet Ethereum
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1207291326067276
=> Feat: Create CPMMGammaPool version for Mainnet Ethereum

contracts/strategies/cpmm/liquidation/CPMMExternalLiquidationStrategy.sol
-fixing order of liquidator and mathlib parameter in CPMMExternalLiquidationStrategy constructor
=> Fix: CPMMExternalLiquidationStrategy constructor liquidator

package.json, yarn.lock
-update v1-core dependency to version 1.2.11
=> Feat: update v1-core dependency

contracts/strategies/cpmm/base/CPMMBaseLongStrategy.sol, package.json
-round up LP tokens when calculating repayment amounts
=> Feat: round up tokens when repaying
